### PR TITLE
Fixed a crash due to misconfigured entries in longopts

### LINKED ISSUE #2: Crash when using `--squash-uids` flag
I had a script that used `--squash-uids` flag, and it is not working anymore with this `genext2fs`.

```
genext2fs --squash-uids
Segmentation fault (core dumped)
```

While the original don't have this issue:

```
/usr/bin/genext2fs --squash-uids
/usr/bin/genext2fs: Not enough arguments. Try --help or else see the man page.
```

### PR DESCRIPTION
**Pull request by mpolitzer**
closes #2

### CODE REVIEW

File: genext2fs.c [hunk 1]
```diff
@@ -3863,8 +3863,8 @@ main(int argc, char **argv)
 	  { "fill-value",	required_argument,	NULL, 'e' },
 	  { "allow-holes",	no_argument,		NULL, 'z' },
 	  { "faketime",		no_argument,		NULL, 'f' },
-	  { "squash",		no_argument,		NULL, 'q' },
-	  { "squash-uids",	no_argument,		NULL, 'U' },
+	  { "squash",		required_argument,	NULL, 'q' },
```
Comment (edubart) [inline genext2fs.c:3866]: `--help` needs update for `--squash <uid>`.

**Review by edubart — APPROVED** [review]
